language: node_js
node_js:
  - 12
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database contact_reminder_test;' -U postgres
  - npm run build
  - npm install -g sequelize-cli
  - sequelize db:migrate
  - sequelize db:seed:all
script:
  - npm test
after_success:
  - npm run test:coverage

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
